---
# start up
start_up:
  mode: scratch
  resume_epoch: 0

  model_name: D2STGNN
  device: cuda:0
  load_pkl: False

data_args:
  data_dir: datasets/CHUNGNAM
  adj_data_path: datasets/sensor_graph/adj_chungnam.pkl
  adj_type: doubletransition

model_args:
  batch_size: 32
  num_feat: 1
  num_hidden: 32
  node_hidden: 10
  time_emb_dim: 10
  dropout: 0.1
  seq_length: 12
  k_t: 3
  k_s: 2
  gap: 3
  num_modalities: 2

optim_args:
  lrate: 0.002
  print_model: False
  wdecay: 1.0e-5
  eps: 1.0e-8
  lr_schedule: True
  lr_sche_steps: [1, 30, 38, 46, 54, 62, 70, 80, 100, 110]
  lr_decay_ratio: 0.75

  if_cl: True
  cl_epochs: 6
  output_seq_len: 12
  warm_epochs: 0

  epochs: 300
  patience: 30
  seq_length: 12
